import {
  AdminPanelSettings,
  Inventory,
  PrecisionManufacturing,
  Verified,
  BuildCircle,
  LocalShipping,
  Storefront,
  Person,
  PersonAdd,
  ManageAccounts,
  TrendingUp,
  AddBox,
  QrCodeScanner,
  Build,
  Assignment,
  Inventory2,
  GppGood,
  Security,
  Watch,
  TrackChanges,
  LocationOn,
  Sell,
  ShoppingCart,
  Favorite,
  SupervisedUserCircle,
  Collections,
  Analytics,
  Timeline,
  AutoAwesome,
  Shield,
  Speed,
  Diamond,
} from "@mui/icons-material";

export const dashboardConfigs = {
  admin: {
    role: "Administrator",
    title: "Administrator Dashboard",
    subtitle: "Administrative Control",
    primaryColor: "#00f5ff",
    secondaryColor: "#0091ea",
    accentColor: "#ff4081",

    stats: [
      {
        icon: SupervisedUserCircle,
        value: 127,
        label: "Active Network Users",
        progress: 85,
        color: "#00e676",
        trend: "+12%",
      },
      {
        icon: TrendingUp,
        value: 89,
        label: "System Performance",
        progress: 89,
        color: "#00b0ff",
        trend: "+5%",
      },
      {
        icon: Security,
        value: "99.9%",
        label: "Security Index",
        progress: 99,
        color: "#ffc107",
        trend: "Optimal",
      },
      {
        icon: Analytics,
        value: 5,
        label: "Pending Operations",
        progress: 20,
        color: "#ff5722",
        trend: "-2",
      },
    ],
    actionCards: [
      {
        title: "Create User Account",
        description: "Deploy new user credentials with blockchain verification",
        icon: PersonAdd,
        path: "/add-account",
        color: "#00e676",
        glow: true,
      },
      {
        title: "Account Management",
        description: "Monitor and control user permissions across the network",
        icon: ManageAccounts,
        path: "/manage-account",
        color: "#00b0ff",
        glow: true,
      },
      {
        title: "System Analytics",
        description: "Real-time network performance and security monitoring",
        icon: Analytics,
        path: "/admin",
        color: "#ff4081",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Network Activity Feed",
      items: [
        "🔹 Luxury supplier onboarded - Blockchain verified • 2h ago",
        "🔹 System backup completed - Zero downtime achieved • 4h ago",
        "🔹 Security audit passed - All protocols validated • 1d ago",
        "🔹 Performance optimization deployed - 15% speed increase • 2d ago",
      ],
    },
    statusItems: {
      title: "System Health Matrix",
      items: [
        {
          label: "Blockchain Network",
          value: "SYNCHRONIZED",
          color: "#00e676",
        },
        { label: "Database Cluster", value: "OPTIMIZED", color: "#00b0ff" },
        { label: "API Gateway", value: "RESPONSIVE", color: "#ffc107" },
        { label: "Security Shield", value: "MAXIMUM", color: "#ff4081" },
      ],
    },
    additionalInfo: {
      title: "Neural Network Command Center",
    },
  },

  supplier: {
    role: "Supplier",
    title: "Supplier Dashboard",
    subtitle: "Premium Raw Material Authentication Center",
    primaryColor: "#4caf50",
    secondaryColor: "#8bc34a",
    accentColor: "#00e676",
    icon: Inventory,
    stats: [
      {
        icon: Diamond,
        value: 45,
        label: "Premium Materials Certified",
        progress: 85,
        color: "#4caf50",
        trend: "+8",
      },
      {
        icon: Timeline,
        value: 32,
        label: "Active Supply Chains",
        progress: 75,
        color: "#00e676",
        trend: "+12%",
      },
      {
        icon: AutoAwesome,
        value: "98.5%",
        label: "Purity Rating",
        progress: 98,
        color: "#00b0ff",
        trend: "Excellent",
      },
      {
        icon: LocalShipping,
        value: 8,
        label: "Delivery Queue",
        progress: 30,
        color: "#ff9800",
        trend: "Processing",
      },
    ],
    actionCards: [
      {
        title: "Register Premium Material",
        description: "Authenticate and immortalize raw materials on blockchain",
        icon: AddBox,
        path: "/register-raw-material",
        color: "#4caf50",
        glow: true,
      },
      {
        title: "Scan QR Scanner",
        description: "Advanced material verification and traceability",
        icon: QrCodeScanner,
        path: "/scanner",
        color: "#00b0ff",
        glow: true,
      },
      {
        title: "Material Inventory",
        description: "Explore your certified material collection",
        icon: Collections,
        path: "/ListRaw",
        color: "#ff9800",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Material Authentication Log",
      items: [
        "💎 Swiss Gold 24K - Genesis Block Created • 2h ago",
        "⚡ Titanium Grade 5 - Origin Verified • 5h ago",
        "🔷 Sapphire Crystal - Purity Confirmed • 1d ago",
        "🔸 Italian Leather Premium - Origin Validated • 2d ago",
      ],
    },
    statusItems: {
      title: "Quality Assurance Matrix",
      items: [
        { label: "Material Authenticity", value: "VERIFIED", color: "#4caf50" },
        { label: "Origin Traceability", value: "CONFIRMED", color: "#00e676" },
        { label: "Blockchain Ledger", value: "IMMUTABLE", color: "#00b0ff" },
        { label: "Compliance Status", value: "CERTIFIED", color: "#ff9800" },
      ],
    },
    additionalInfo: {
      title: "Premium Material Genesis Point",
    },
  },

  manufacturer: {
    role: "Manufacturer",
    title: "Manufacturer Dashboard",
    subtitle: "Component Manufacturing Hub",
    primaryColor: "#ff9800",
    secondaryColor: "#ff5722",
    accentColor: "#ffab00",
    icon: PrecisionManufacturing,
    stats: [
      {
        icon: Build,
        value: 128,
        label: "Components Forged",
        progress: 85,
        color: "#ff9800",
        trend: "+15",
      },
      {
        icon: Speed,
        value: 45,
        label: "Active Production Lines",
        progress: 65,
        color: "#ff5722",
        trend: "Running",
      },
      {
        icon: AutoAwesome,
        value: "96.8%",
        label: "Precision Rating",
        progress: 96,
        color: "#00b0ff",
        trend: "Excellent",
      },
      {
        icon: Inventory2,
        value: 67,
        label: "Materials Consumed",
        progress: 70,
        color: "#9c27b0",
        trend: "Optimal",
      },
    ],
    actionCards: [
      {
        title: "Create Component",
        description: "Transform premium materials into precision components",
        icon: Build,
        path: "/create-component",
        color: "#ff9800",
        glow: true,
      },
      {
        title: "Scan Raw Material",
        description: "Verify raw material authenticity before production",
        icon: QrCodeScanner,
        path: "/scanner",
        color: "#00b0ff",
        glow: true,
      },
      {
        title: "Materials Inventory",
        description: "Manage your precision-crafted component inventory",
        icon: Inventory2,
        path: "/list-components",
        color: "#4caf50",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Manufacturing Timeline",
      items: [
        "⚙️ Swiss Movement Core #SMC-2024-001 - Precision Forged • 1h ago",
        "🔧 Titanium Case Shell #TCS-2024-045 - Quality Assured • 3h ago",
        "⭐ Diamond-Cut Dial #DCD-2024-023 - Perfection Achieved • 6h ago",
        "🎯 Precision Hands Set #PHS-2024-012 - Calibrated • 8h ago",
      ],
    },
    statusItems: {
      title: "Production Control Matrix",
      items: [
        { label: "Quality Control", value: "ACTIVE", color: "#4caf50" },
        { label: "Equipment Status", value: "OPTIMAL", color: "#ff9800" },
        { label: "Material Flow", value: "SYNCHRONIZED", color: "#00b0ff" },
        { label: "Output Efficiency", value: "MAXIMUM", color: "#9c27b0" },
      ],
    },
    additionalInfo: {
      title: "Precision Engineering Command Center",
    },
  },

  certifier: {
    role: "Certifier",
    title: "Certifier Dashboard",
    subtitle: "Certification & Verification Hub",
    primaryColor: "#2196f3",
    secondaryColor: "#03a9f4",
    accentColor: "#00b0ff",
    icon: Verified,
    stats: [
      {
        icon: Shield,
        value: 89,
        label: "Components Validated",
        progress: 85,
        color: "#2196f3",
        trend: "+7",
      },
      {
        icon: Assignment,
        value: 12,
        label: "In Validation Queue",
        progress: 40,
        color: "#ff9800",
        trend: "Processing",
      },
      {
        icon: AutoAwesome,
        value: "99.2%",
        label: "Accuracy Score",
        progress: 99,
        color: "#00e676",
        trend: "Perfect",
      },
      {
        icon: Security,
        value: 3,
        label: "Quality Issues Detected",
        progress: 15,
        color: "#f44336",
        trend: "Low",
      },
    ],
    actionCards: [
      {
        title: "Certify Component",
        description:
          "Advanced quality verification with blockchain certification",
        icon: GppGood,
        path: "/certify-component",
        color: "#2196f3",
        glow: true,
      },
      {
        title: "Scan Component QR Code",
        description: "Deep scan and authenticate component integrity",
        icon: QrCodeScanner,
        path: "/scanner",
        color: "#00b0ff",
        glow: true,
      },
      {
        title: "Component Reviews",
        description: "Browse certified component database",
        icon: Security,
        path: "/components-review",
        color: "#ff9800",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Certification Timeline",
      items: [
        "✅ Component #SMC-2024-001 - CERTIFIED EXCELLENT • 1h ago",
        "✅ Component #TCS-2024-045 - CERTIFIED PREMIUM • 3h ago",
        "⏳ Component #DCD-2024-023 - UNDER REVIEW • 6h ago",
        "❌ Component #PHS-2024-012 - QUALITY ISSUE DETECTED • 8h ago",
      ],
    },
    statusItems: {
      title: "Certification Standards Matrix",
      items: [
        { label: "Material Analysis", value: "ACTIVE", color: "#2196f3" },
        { label: "ISO Standards", value: "COMPLIANT", color: "#00e676" },
        { label: "Blockchain Records", value: "PERMANENT", color: "#9c27b0" },
        { label: "Authority Level", value: "MAXIMUM", color: "#ff9800" },
      ],
    },
    additionalInfo: {
      title: "Quality Assurance Command Center",
    },
  },

  assembler: {
    role: "Assembler",
    title: "Assembler Dashboard",
    subtitle: "Luxury Watch Assembly Laboratory",
    primaryColor: "#673ab7",
    secondaryColor: "#9c27b0",
    accentColor: "#e91e63",
    icon: BuildCircle,
    stats: [
      {
        icon: Watch,
        value: 34,
        label: "Timepieces Crafted",
        progress: 75,
        color: "#673ab7",
        trend: "+5",
      },
      {
        icon: BuildCircle,
        value: 8,
        label: "Active Assembly Lines",
        progress: 45,
        color: "#9c27b0",
        trend: "Crafting",
      },
      {
        icon: AutoAwesome,
        value: "98.7%",
        label: "Craftsmanship Score",
        progress: 98,
        color: "#00b0ff",
        trend: "Masterful",
      },
      {
        icon: Assignment,
        value: 156,
        label: "Components Assembled",
        progress: 85,
        color: "#ff9800",
        trend: "Precise",
      },
    ],
    actionCards: [
      {
        title: "Assemble Watch",
        description: "Assemble certified components into masterpiece watches",
        icon: BuildCircle,
        path: "/assemble-watch",
        color: "#673ab7",
        glow: true,
      },
      {
        title: "Component Scanner",
        description: "Verify certified component authenticity before assembly",
        icon: QrCodeScanner,
        path: "/scanner",
        color: "#00b0ff",
        glow: true,
      },
      {
        title: "Watches Inventory",
        description: "Showcase your assembled luxury watch collection",
        icon: Collections,
        path: "/list-watches",
        color: "#4caf50",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Assembly Masterwork Log",
      items: [
        "⌚ Luxury Chronograph #LC-2024-001 - MASTERPIECE COMPLETED • 2h ago",
        "🎯 Premium Diver #PD-2024-045 - ASSEMBLY IN PROGRESS • 4h ago",
        "✨ Elite Dress Watch #EDW-2024-023 - FINAL TESTING • 1d ago",
        "🏆 Classic Heritage #CH-2024-012 - QUALITY PERFECTED • 2d ago",
      ],
    },
    statusItems: {
      title: "Assembly Requirements Matrix",
      items: [
        {
          label: "Component Certification",
          value: "MANDATORY",
          color: "#673ab7",
        },
        {
          label: "Minimum Standards",
          value: "MOVEMENT + CASE + DIAL",
          color: "#9c27b0",
        },
        { label: "Quality Assurance", value: "RIGOROUS", color: "#00b0ff" },
        { label: "Blockchain Proof", value: "IMMUTABLE", color: "#ff9800" },
      ],
    },
    additionalInfo: {
      title: "Master Horological Laboratory",
    },
  },

  distributor: {
    role: "Distributor",
    title: "Distributor Dashboard",
    subtitle: "Worldwide Distribution Network",
    primaryColor: "#00bcd4",
    secondaryColor: "#26c6da",
    accentColor: "#00acc1",
    icon: LocalShipping,
    stats: [
      {
        icon: LocalShipping,
        value: 67,
        label: "Timepieces in Transit",
        progress: 75,
        color: "#00bcd4",
        trend: "+12",
      },
      {
        icon: TrackChanges,
        value: 23,
        label: "Real-time Tracking",
        progress: 35,
        color: "#ff9800",
        trend: "Live",
      },
      {
        icon: LocationOn,
        value: 89,
        label: "Successful Deliveries",
        progress: 90,
        color: "#4caf50",
        trend: "+8%",
      },
      {
        icon: Speed,
        value: 4.2,
        label: "Avg. Delivery (Days)",
        progress: 75,
        color: "#9c27b0",
        trend: "Fast",
      },
    ],
    actionCards: [
      {
        title: "Update Shipping",
        description: "Real-time shipping status and route optimization",
        icon: TrackChanges,
        path: "/update-shipping",
        color: "#00bcd4",
        glow: true,
      },
      {
        title: "Tracking Scanner",
        description: "Advanced QR scanning for shipment authentication",
        icon: QrCodeScanner,
        path: "/scanner",
        color: "#4caf50",
        glow: true,
      },
      {
        title: "Watches Tracking",
        description: "Comprehensive shipping management dashboard",
        icon: LocalShipping,
        path: "/watches-shipping",
        color: "#ff9800",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Global Shipping Operations",
      items: [
        "🚀 Timepiece #LC-2024-001 - DELIVERED NYC • Blockchain Confirmed • 2h ago",
        "✈️ Timepiece #PD-2024-045 - IN TRANSIT London • GPS Tracked • 4h ago",
        "🌍 Timepiece #EDW-2024-023 - SHIPPED Tokyo • Route Optimized • 1d ago",
        "📦 Timepiece #CH-2024-012 - AWAITING DISPATCH • Priority Queue • 2d ago",
      ],
    },
    statusItems: {
      title: "Logistics Network Status",
      items: [
        { label: "Fleet Operations", value: "SYNCHRONIZED", color: "#4caf50" },
        { label: "Global Coverage", value: "WORLDWIDE", color: "#00bcd4" },
        { label: "Tracking System", value: "REAL-TIME", color: "#ff9800" },
        { label: "Blockchain Ledger", value: "VERIFIED", color: "#9c27b0" },
      ],
    },
    additionalInfo: {
      title: "Logistics Network",
    },
  },

  retailer: {
    role: "Retailer",
    title: "Retailer Dashboard",
    subtitle: "Premium Timepiece Sales Hub",
    primaryColor: "#e91e63",
    secondaryColor: "#ad1457",
    accentColor: "#c2185b",
    icon: Storefront,
    stats: [
      {
        icon: Diamond,
        value: 34,
        label: "Premium Collection",
        progress: 68,
        color: "#e91e63",
        trend: "+6",
      },
      {
        icon: TrendingUp,
        value: 12,
        label: "Sales This Month",
        progress: 35,
        color: "#4caf50",
        trend: "+15%",
      },
      {
        icon: AutoAwesome,
        value: "97.8%",
        label: "Client Satisfaction",
        progress: 97,
        color: "#00b0ff",
        trend: "Excellent",
      },
      {
        icon: Collections,
        value: 156,
        label: "Boutique Inventory",
        progress: 78,
        color: "#ff9800",
        trend: "Curated",
      },
    ],
    actionCards: [
      {
        title: "Mark Available",
        description: "Feature luxury timepieces in your premium collection",
        icon: Sell,
        path: "/mark-available",
        color: "#e91e63",
        glow: true,
      },
      {
        title: "Scan Watch QR Code",
        description: "Verify timepiece authenticity and provenance",
        icon: QrCodeScanner,
        path: "/scanner",
        color: "#00b0ff",
        glow: true,
      },
      {
        title: "Watches Catalog",
        description: "Explore your curated timepiece collection",
        icon: Collections,
        path: "/watches-catalog",
        color: "#4caf50",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Boutique Sales Activity",
      items: [
        "💎 Chronograph #LC-2024-001 - SOLD $25,000 • VIP Client • 2h ago",
        "⭐ Dress Watch #EDW-2024-045 - FEATURED $32,500 • Premium Display • 4h ago",
        "🏆 Heritage #CH-2024-023 - SOLD $28,750 • Collector Edition • 1d ago",
        "✨ Diver #PD-2024-012 - RESERVED $15,000 • Exclusive Preview • 2d ago",
      ],
    },
    statusItems: {
      title: "Boutique Operations Matrix",
      items: [
        { label: "Boutique Status", value: "PREMIUM", color: "#4caf50" },
        { label: "Inventory System", value: "REAL-TIME", color: "#00b0ff" },
        { label: "Client Services", value: "CONCIERGE", color: "#ff9800" },
        { label: "Payment Security", value: "BLOCKCHAIN", color: "#e91e63" },
      ],
    },
    additionalInfo: {
      title: "Elite Timepiece Boutique",
    },
  },

  consumer: {
    role: "Consumer",
    title: "Consumer Dashboard",
    subtitle: "Personal Luxury Timepiece Portfolio",
    primaryColor: "#ff6f00",
    secondaryColor: "#ff8f00",
    accentColor: "#ffab00",
    icon: Person,
    stats: [
      {
        icon: Diamond,
        value: 3,
        label: "Authenticated Timepieces",
        progress: 60,
        color: "#ff6f00",
        trend: "Premium",
      },
      {
        icon: Favorite,
        value: 7,
        label: "Wishlist Collection",
        progress: 35,
        color: "#e91e63",
        trend: "Curated",
      },
      {
        icon: Shield,
        value: "100%",
        label: "Authenticity Guarantee",
        progress: 100,
        color: "#4caf50",
        trend: "Verified",
      },
      {
        icon: TrendingUp,
        value: "$78.5K",
        label: "Portfolio Value",
        progress: 75,
        color: "#00b0ff",
        trend: "+12%",
      },
    ],
    actionCards: [
      {
        title: "Purchase Watch",
        description: "Browse and acquire authenticated luxury timepieces",
        icon: ShoppingCart,
        path: "/purchase-watch",
        color: "#ff6f00",
        glow: true,
      },
      {
        title: "Verify Scanner",
        description: "Scan and verify timepiece authenticity instantly",
        icon: QrCodeScanner,
        path: "/scanner",
        color: "#00b0ff",
        glow: true,
      },
      {
        title: "My Collection",
        description: "Manage your personal luxury timepiece portfolio",
        icon: Collections,
        path: "/watch-collection",
        color: "#e91e63",
        glow: true,
      },
    ],
    recentActivities: {
      title: "Personal Collection Chronicle",
      items: [
        "💎 Patek Philippe Nautilus #PPM-2024-001 - AUTHENTICATED • Blockchain Verified",
        "⭐ Rolex Submariner #RSM-2024-023 - AUTHENTICATED • Heritage Confirmed",
        "🏆 Omega Speedmaster #OSM-2024-045 - AUTHENTICATED • Apollo Legacy",
        "✨ [Discover more exclusive timepieces in premium boutiques...]",
      ],
    },
    statusItems: {
      title: "Collector Benefits Matrix",
      items: [
        {
          label: "Authentication Status",
          value: "BLOCKCHAIN VERIFIED",
          color: "#4caf50",
        },
        { label: "Digital Certificate", value: "IMMUTABLE", color: "#00b0ff" },
        { label: "Full Provenance", value: "TRACEABLE", color: "#e91e63" },
        { label: "Transfer Rights", value: "UNLIMITED", color: "#ff9800" },
      ],
    },
    additionalInfo: {
      title: "Elite Collector's Sanctuary",
    },
  },
};
